# Generated by Django 3.0 on 2019-12-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedmeme',
            old_name='image',
            new_name='meme_image',
        ),
        migrations.AddField(
            model_name='finishedmeme',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finishedmeme',
            name='top_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
