# Generated by Django 3.0 on 2019-12-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0002_auto_20191217_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedmeme',
            name='base_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jenny.BaseImage'),
            preserve_default=False,
        ),
    ]
