# Generated by Django 3.0 on 2019-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0003_finishedmeme_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedmeme',
            name='meme_image',
            field=models.ImageField(upload_to='images/memes/'),
        ),
    ]
