# Generated by Django 3.0 on 2019-12-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0004_auto_20191217_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedmeme',
            name='base_image',
            field=models.ForeignKey(help_text='image for the meme', on_delete=django.db.models.deletion.CASCADE, to='jenny.BaseImage'),
        ),
        migrations.AlterField(
            model_name='finishedmeme',
            name='bottom_text',
            field=models.CharField(blank=True, help_text='text at the bottom of the meme', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishedmeme',
            name='title',
            field=models.CharField(help_text='a name for your meme', max_length=250),
        ),
        migrations.AlterField(
            model_name='finishedmeme',
            name='top_text',
            field=models.CharField(blank=True, help_text='text at the top of the meme', max_length=100, null=True),
        ),
    ]
