# Generated by Django 3.0 on 2019-12-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0005_auto_20191217_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/memes/')),
            ],
        ),
        migrations.AlterField(
            model_name='finishedmeme',
            name='meme_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenny.MemeImage'),
        ),
    ]
