# Generated by Django 3.0 on 2019-12-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenny', '0007_auto_20191218_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedmeme',
            name='meme_image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jenny.MemeImage'),
        ),
    ]
